# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 644e8928e54bf9fd124d5c0d7e691ce1000f88b92fd3180ee972ee5a835df8340a7b1c98d05d3026d2f180891918fc6af14f9175e386708ab0ad5dd9054aef63

test:
  secret_key_base: 4600d6f207fd124aa761dc54ab2a52bb8a49f3619f4bfac4bc06aa0654cd61e97c63bd1cdf6cd6ebce4cf2b3802d5c6aa36f1fe30fa04262ec07baa99d516aa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
